name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:

  check:
    runs-on: ubuntu-latest
    name: Check w/ ${{ matrix.deno-version }}
    strategy:
      matrix:
        deno-version:
        - v1.35
        - v1.37
        - v1.39
        - v1.43
        - v2.0
        - v2.1
        - canary
      fail-fast: false # run each branch to completion

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno-version }}

    # "https" cache: code from the Internet
    # External sources won't change much so we use less precise keys
    - name: Cache https://
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/deno/deps/https
          ~/.cache/deno/remote/https
        key: deno/${{ matrix.deno-version }}-https/v1-${{ github.sha }}
        restore-keys: deno-https/v1-

    - name: Check demo.ts
      run: time deno check --unstable demo.ts

    # - name: Run tests
    #   run: time deno test --allow-net=localhost --allow-read=/proc/self
