name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    name: Deno ${{ matrix.deno-version }}
    strategy:
      matrix:
        deno-version: ["v1.7", "v1.8", "v1.9", "canary"]

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@main
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Check demo.ts
      run: time deno cache demo.ts

    - name: Run tests
      run: time deno test --allow-net=localhost --allow-read=/proc/self
